command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"

env:
  - name: CATALOG
    value: shm
  - name: SCHEMA
    value: graph
  - name: MLFLOW_EXPERIMENT_NAME
    value: /Shared/taxonomy-mapping-agent

resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "b5d9b3c3fc993bf3"
      permission: CAN_USE
